// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhFMhPbzn0SaWy_QXL7jb7cN9FkaYfaA',
    appId: '1:815550173536:android:fecee36d7ecdcf9796ce05',
    messagingSenderId: '815550173536',
    projectId: 'personal-projects-185413',
    databaseURL: 'https://personal-projects-185413.firebaseio.com',
    storageBucket: 'personal-projects-185413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwogLZE9wGzqjtKiD7JNfQAl-wDY3thjs',
    appId: '1:815550173536:ios:a99ec165d868fb4996ce05',
    messagingSenderId: '815550173536',
    projectId: 'personal-projects-185413',
    databaseURL: 'https://personal-projects-185413.firebaseio.com',
    storageBucket: 'personal-projects-185413.appspot.com',
    iosClientId:
        '815550173536-soft2acarie0v5qsh31jba0q9up7q8vn.apps.googleusercontent.com',
    iosBundleId: 'dev.dcm.app',
  );
}
