include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  extends:
    - recommended
  rules:
    - avoid-slow-collection-methods
    - avoid-single-child-column-or-row
    - prefer-bytes-builder
    - prefer-declaring-const-constructor
    - avoid-map-keys-contains
    - avoid-border-all
    - avoid-incorrect-image-opacity
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - pass-existing-future-to-future-builder
    - pass-existing-stream-to-stream-builder
    - prefer-const-border-radius
    - prefer-dedicated-media-query-methods
    - prefer-match-file-name: true
    - avoid-undisposed-instances:
        ignored-instances:
          - SomeClass
        ignored-invocations:
          - WithAutoDispose
    - arguments-ordering:
        alphabetize: true
        first:
          - some
          - name
        last:
          - child
          - children
  exclude:
    parameters:
      - lib/generated/**
  metrics:
    halstead-volume: 50
    cyclomatic-complexity: 10
    lines-of-code: 10
    maximum-nesting-level: 5
